[project]
name = "lab2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.124.4",
    "httpx>=0.28.1",
    "peewee>=3.18.3",
    "peewee-migrate>=1.14.3",
    "requests>=2.32.5",
]
